### ISSUE TITLE
Dxx don't work with crt in cmake,  if you have free time, i will send you the number of 5 cmakelist.txt, thank you.

### ISSUE THREAD

**Issue by ddkwork** [sidyhe/dxx#1]

**Comment by sidyhe** [comment]
PR please

**Comment by ddkwork** [comment]
> PR please

cmake_minimum_required(VERSION "3.15")

project(EASTL)
set(CMAKE_CXX_STANDARD 17)

list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}")
find_package(WDK REQUIRED)

include_directories(
        /
        kcrt/
        kstl/
        kxml/pugixml/
        lua/lua/
        lua/lua/core/
        lua/lua/luaplus/
        msgpack/
        msgpack/msgpack/

)

aux_source_directory(kcrt kcrt)
aux_source_directory(kstl kstl)
aux_source_directory(kxml kxml)
aux_source_directory(lua lua)
aux_source_directory(msgpack msgpack)
#aux_source_directory( )
#aux_source_directory( )
#aux_source_directory( )

wdk_add_driver(EASTL
        ${kcrt}
        ${kstl}
        ${kxml}
        ${lua}
        ${msgpack}
        )

#link_libraries(zydisRing0 ${CMAKE_CURRENT_LIST_DIR}/zydisRing0)
